"""add_region_alias

Revision ID: 12a08a19f93b
Revises: a9f15a698e73
Create Date: 2026-08-20 17:31:21.609326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a08a19f93b'
down_revision: Union[str, Sequence[str], None] = 'a9f15a698e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('alias', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'alias')
    # ### end Alembic commands ###
