"""add_electrical_params_to_equipment

Revision ID: 1d117bc5be9d
Revises: 3a4555b3328c
Create Date: 2026-08-20 14:46:18.606628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d117bc5be9d'
down_revision: Union[str, Sequence[str], None] = '3a4555b3328c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
