"""split_generator_catalog_and_instance

Revision ID: 267cb602e877
Revises: 76f3c35071a0
Create Date: 2026-09-01 12:32:45.421038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267cb602e877'
down_revision: Union[str, Sequence[str], None] = '76f3c35071a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generator_class',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nominal_capacity_mw', sa.Float(), nullable=True),
    sa.Column('failure_rate_percent', sa.Float(), nullable=True),
    sa.Column('repair_time_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generator_class_system_id'), 'generator_class', ['system_id'], unique=False)
    op.add_column('generator', sa.Column('generator_class_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_generator_generator_class_id'), 'generator', ['generator_class_id'], unique=False)
    op.create_foreign_key(None, 'generator', 'generator_class', ['generator_class_id'], ['id'], ondelete='CASCADE')
    op.drop_column('generator', 'repair_time_hours')
    op.drop_column('generator', 'failure_rate_percent')
    op.drop_column('generator', 'nominal_capacity_mw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generator', sa.Column('nominal_capacity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('generator', sa.Column('failure_rate_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('generator', sa.Column('repair_time_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generator', type_='foreignkey')
    op.drop_index(op.f('ix_generator_generator_class_id'), table_name='generator')
    op.drop_column('generator', 'generator_class_id')
    op.drop_index(op.f('ix_generator_class_system_id'), table_name='generator_class')
    op.drop_table('generator_class')
    # ### end Alembic commands ###
