"""Create Time Series Tables

Revision ID: 76f3c35071a0
Revises: 1839b446dcc8
Create Date: 2026-08-24 15:33:37.573482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76f3c35071a0'
down_revision: Union[str, Sequence[str], None] = '1839b446dcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_series_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('series_type', sa.String(), nullable=False),
    sa.Column('data_position', sa.String(), nullable=False),
    sa.Column('unit_x', sa.String(), nullable=True),
    sa.Column('unit_y', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_time_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metadata_id', sa.Uuid(), nullable=False),
    sa.Column('values', postgresql.ARRAY(sa.FLOAT()), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['time_series_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metadata_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_time_series')
    op.drop_table('time_series_metadata')
    # ### end Alembic commands ###
