"""add_confidence_json

Revision ID: 81714934fdf0
Revises: 52a62d030302
Create Date: 2026-08-21 00:13:08.558569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81714934fdf0'
down_revision: Union[str, Sequence[str], None] = '52a62d030302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reliability_result', sa.Column('confidence_intervals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reliability_result', 'confidence_intervals')
    # ### end Alembic commands ###
