"""Add Region and Bus tables

Revision ID: 9cda931cf233
Revises: e580308cde1e
Create Date: 2026-08-18 09:41:47.268023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cda931cf233'
down_revision: Union[str, Sequence[str], None] = 'e580308cde1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus', sa.Column('base_kv', sa.Float(), nullable=True))
    op.alter_column('bus', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('bus', 'nominal_voltage_kv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus', sa.Column('nominal_voltage_kv', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.alter_column('bus', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bus', 'base_kv')
    # ### end Alembic commands ###
