"""add_electrical_params_to_equipment

Revision ID: a9f15a698e73
Revises: 1d117bc5be9d
Create Date: 2026-08-20 14:54:07.446034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f15a698e73'
down_revision: Union[str, Sequence[str], None] = '1d117bc5be9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generator', 'nominal_capacity_mw',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('generator', 'failure_rate_percent',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('generator', 'repair_time_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('transformer', sa.Column('r_pu', sa.Float(), nullable=True))
    op.add_column('transformer', sa.Column('x_pu', sa.Float(), nullable=True))
    op.add_column('transformer', sa.Column('failure_rate', sa.Float(), nullable=True))
    op.add_column('transformer', sa.Column('repair_time', sa.Float(), nullable=True))
    op.alter_column('transformer', 'capacity_mva',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('transmission_line', sa.Column('r_pu', sa.Float(), nullable=True))
    op.add_column('transmission_line', sa.Column('x_pu', sa.Float(), nullable=True))
    op.add_column('transmission_line', sa.Column('capacity_mva', sa.Float(), nullable=True))
    op.add_column('transmission_line', sa.Column('failure_rate', sa.Float(), nullable=True))
    op.add_column('transmission_line', sa.Column('repair_time', sa.Float(), nullable=True))
    op.drop_column('transmission_line', 'capacity_mw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transmission_line', sa.Column('capacity_mw', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('transmission_line', 'repair_time')
    op.drop_column('transmission_line', 'failure_rate')
    op.drop_column('transmission_line', 'capacity_mva')
    op.drop_column('transmission_line', 'x_pu')
    op.drop_column('transmission_line', 'r_pu')
    op.alter_column('transformer', 'capacity_mva',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('transformer', 'repair_time')
    op.drop_column('transformer', 'failure_rate')
    op.drop_column('transformer', 'x_pu')
    op.drop_column('transformer', 'r_pu')
    op.alter_column('generator', 'repair_time_hours',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('generator', 'failure_rate_percent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('generator', 'nominal_capacity_mw',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
