"""Init clean schema with Flat ReliabilityResult

Revision ID: bc234ca72247
Revises: 
Create Date: 2026-08-18 08:56:14.231951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc234ca72247'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'VALIDATING', 'INGESTING', 'READY', 'PARTIAL', 'FAILED', 'ARCHIVED', name='casestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_external_name'), 'case', ['external_name'], unique=False)
    op.create_table('simulation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('results_directory', sa.String(), nullable=True),
    sa.Column('simulated_years', sa.Integer(), nullable=True),
    sa.Column('simulation_time', sa.Interval(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('system_representation', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reliability_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('bus_external_id', sa.String(), nullable=True),
    sa.Column('lolp', sa.Float(), nullable=False),
    sa.Column('lole', sa.Float(), nullable=False),
    sa.Column('epns', sa.Float(), nullable=False),
    sa.Column('eens', sa.Float(), nullable=False),
    sa.Column('lolf', sa.Float(), nullable=False),
    sa.Column('lold', sa.Float(), nullable=False),
    sa.Column('lolc', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('parameter_key', sa.String(), nullable=False),
    sa.Column('parameter_value', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_config_simulation_run_id'), 'simulation_config', ['simulation_run_id'], unique=False)
    op.create_table('system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('external_name', sa.String(), nullable=False),
    sa.Column('nominal_load_mw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_system_id'), 'region', ['system_id'], unique=False)
    op.create_table('bus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nominal_voltage_kv', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_region_id'), 'bus', ['region_id'], unique=False)
    op.create_index(op.f('ix_bus_system_id'), 'bus', ['system_id'], unique=False)
    op.create_table('generator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('bus_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('nominal_capacity_mw', sa.Numeric(), nullable=True),
    sa.Column('failure_rate_percent', sa.Numeric(), nullable=True),
    sa.Column('repair_time_hours', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generator_bus_id'), 'generator', ['bus_id'], unique=False)
    op.create_index(op.f('ix_generator_system_id'), 'generator', ['system_id'], unique=False)
    op.create_table('transformer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('from_bus_id', sa.Uuid(), nullable=False),
    sa.Column('to_bus_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity_mva', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['from_bus_id'], ['bus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_bus_id'], ['bus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformer_from_bus_id'), 'transformer', ['from_bus_id'], unique=False)
    op.create_index(op.f('ix_transformer_system_id'), 'transformer', ['system_id'], unique=False)
    op.create_index(op.f('ix_transformer_to_bus_id'), 'transformer', ['to_bus_id'], unique=False)
    op.create_table('transmission_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('from_bus_id', sa.Uuid(), nullable=False),
    sa.Column('to_bus_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity_mw', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['from_bus_id'], ['bus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_bus_id'], ['bus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmission_line_from_bus_id'), 'transmission_line', ['from_bus_id'], unique=False)
    op.create_index(op.f('ix_transmission_line_system_id'), 'transmission_line', ['system_id'], unique=False)
    op.create_index(op.f('ix_transmission_line_to_bus_id'), 'transmission_line', ['to_bus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transmission_line_to_bus_id'), table_name='transmission_line')
    op.drop_index(op.f('ix_transmission_line_system_id'), table_name='transmission_line')
    op.drop_index(op.f('ix_transmission_line_from_bus_id'), table_name='transmission_line')
    op.drop_table('transmission_line')
    op.drop_index(op.f('ix_transformer_to_bus_id'), table_name='transformer')
    op.drop_index(op.f('ix_transformer_system_id'), table_name='transformer')
    op.drop_index(op.f('ix_transformer_from_bus_id'), table_name='transformer')
    op.drop_table('transformer')
    op.drop_index(op.f('ix_generator_system_id'), table_name='generator')
    op.drop_index(op.f('ix_generator_bus_id'), table_name='generator')
    op.drop_table('generator')
    op.drop_index(op.f('ix_bus_system_id'), table_name='bus')
    op.drop_index(op.f('ix_bus_region_id'), table_name='bus')
    op.drop_table('bus')
    op.drop_index(op.f('ix_region_system_id'), table_name='region')
    op.drop_table('region')
    op.drop_table('system')
    op.drop_index(op.f('ix_simulation_config_simulation_run_id'), table_name='simulation_config')
    op.drop_table('simulation_config')
    op.drop_table('reliability_result')
    op.drop_table('source_file')
    op.drop_table('simulation_run')
    op.drop_index(op.f('ix_case_external_name'), table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###
