"""add_confidence_json

Revision ID: da3701f0caf6
Revises: e5b7c44bfee8
Create Date: 2026-08-21 16:43:35.525133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3701f0caf6'
down_revision: Union[str, Sequence[str], None] = 'e5b7c44bfee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reliability_result', sa.Column('region_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reliability_result', 'region_name')
    # ### end Alembic commands ###
